# Generated by Django 4.1.7 on 2023-04-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('avarage', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
